### ISSUE TITLE
[Priority] Coin drops per kill

### ISSUE THREAD

**Issue by trickmaulz** [Palidino/BattleScape-Server#30]
Make sure coins drop each time you kill a person. As your kill streak builds up, you get more coins per kill.

**Comment by Palidino** [comment]
Given that I'd like to price at least some items similar to what they're worth on OSRS, what would be a good starting point to try out for coins per kill?

**Comment by trickmaulz** [comment]
@Palidino currently on OSRS, they give you around 100-200k per kill, we could make it around 150-300k/kill but as your kill-streak goes up, so does the reward.

**Comment by Palidino** [comment]
I'm not sure if you're familiar with the emblem system on BS, but it works just like OSRS except that you get BM instead of points. I've taken those and made them give coins instead of made a tier 1 a guaranteed drop while PKing. This way, it'll look more appealing than simply getting a coin drop. Tiers can be upgraded by carrying one when you get a kill at the risk of it turning into coins and dropping for your opponent if you die with it. Not sure if that's good or not to keep but it could be another form of risk PKing for people who want to do it, especially since it'll allow players wanting to risk to actually gain more even if they're fighting players with little to no risk.
